### ISSUE TITLE
Displaying compatible logging options results in segmentation fault

### ISSUE THREAD

**Issue by jamieb133** [luishowell/infotainment-system#2]
LoggerWindow class works fine when passing a test vector of compatible PIDs however crashes when passing reference to an OBD2 object (containing a vector of the actual supported PIDs for a given car).

**Comment by luishowell** [comment]
is there any progress on this? :)

**Comment by jamieb133** [comment]
We'll need to test this in the car but I've discovered that it crashes when writing the parameter name to the file?? very bizarre, I'll hopefully have it sorted in the next hour

**Comment by jamieb133** [comment]
Okay I worked out what it was, there was a mismatch between the string expected by the hash functions and the ones sent by the logging window. (there needed to be the "01" prefix before the PID code). Will close for now
