### ISSUE TITLE
Build fails on non raspberry pi devices

### ISSUE THREAD

**Issue by luishowell** [luishowell/infotainment-system#3]
The program will not build on non-raspberry pi devices or raspberry pis without wiring pi installed. Wiringpi functionality is only required for ultrasonic sensors. Qmake files should be updated to allowing building on other devices.

**Comment by jamieb133** [comment]
Got this working with a pre-processor define but I still need to work out how to exclude linking of wiring-pi for non-rpi builds without having to go and comment out the relevant line in the .pro file.

**Comment by jamieb133** [comment]
Luis found a way of getting around this using the CI server

**Comment by jamieb133** [comment]
to clarify, the install script installs wiringpi for all machines to prevent linker errors. Non-RPI builds must simply remove the RPI define in config.h
